services:
  app:
    image: ghcr.io/goodboyboy666/easydrop:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      EASYDROP_SERVER_MODE: production
      EASYDROP_SERVER_ADDR: :8080
    volumes:
      - ./data:/app/data
