// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"easydrop/internal/config"
	"easydrop/internal/pkg/captcha"
	"easydrop/internal/pkg/database"
	"easydrop/internal/pkg/email"
	"easydrop/internal/pkg/jwt"
	"easydrop/internal/pkg/redis"
	"easydrop/internal/pkg/storage"
	"easydrop/internal/repo"
	"easydrop/internal/service"
)

// Injectors from wire.go:

// Initialize 通过 Wire 组装应用依赖。
func Initialize(configDir string, strict bool) (*App, error) {
	staticConfig, err := config.Load(configDir, strict)
	if err != nil {
		return nil, err
	}
	databaseConfig := config.ProvideDBConfig(staticConfig)
	db, err := database.NewDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	dbConfig, err := config.NewDBConfig(db)
	if err != nil {
		return nil, err
	}
	redisConfig := config.ProvideRedisConfig(staticConfig)
	client, err := redis.NewClient(redisConfig)
	if err != nil {
		return nil, err
	}
	emailConfig := config.ProvideEmailConfig(staticConfig)
	emailClient, err := email.NewClient(emailConfig)
	if err != nil {
		return nil, err
	}
	jwtConfig := config.ProvideJWTConfig(staticConfig)
	manager, err := jwt.NewManager(jwtConfig)
	if err != nil {
		return nil, err
	}
	storageConfig := config.ProvideStorageConfig(staticConfig)
	storageManager, err := storage.NewManager(storageConfig)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(db)
	allCaptchaConfig := config.ProvideCaptchaConfig(staticConfig)
	httpClient := captcha.NewHttpClient()
	verifier, err := captcha.NewVerifier(allCaptchaConfig, httpClient)
	if err != nil {
		return nil, err
	}
	authService := service.NewAuthService(userRepo, dbConfig, manager, verifier)
	attachmentRepo := repo.NewAttachmentRepo(db)
	attachmentService := service.NewAttachmentService(attachmentRepo, userRepo, storageManager)
	commentRepo := repo.NewCommentRepo(db)
	postRepo := repo.NewPostRepo(db)
	commentService := service.NewCommentService(commentRepo, postRepo, userRepo)
	tagRepo := repo.NewTagRepo(db)
	postService := service.NewPostService(postRepo, tagRepo)
	tagService := service.NewTagService(tagRepo)
	userService := service.NewUserService(userRepo)
	app := NewApp(staticConfig, db, dbConfig, client, emailClient, manager, storageManager, authService, attachmentService, commentService, postService, tagService, userService)
	return app, nil
}
