// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"easydrop/internal/config"
	"easydrop/internal/handler"
	"easydrop/internal/middleware"
	"easydrop/internal/pkg/cache"
	"easydrop/internal/pkg/captcha"
	"easydrop/internal/pkg/database"
	"easydrop/internal/pkg/email"
	"easydrop/internal/pkg/jwt"
	"easydrop/internal/pkg/redis"
	"easydrop/internal/pkg/storage"
	"easydrop/internal/pkg/token"
	"easydrop/internal/repo"
	"easydrop/internal/service"
)

// Injectors from wire.go:

// Initialize 通过 Wire 组装应用依赖。
func Initialize(configDir string, strict bool) (*App, error) {
	staticConfig, err := config.Load(configDir, strict)
	if err != nil {
		return nil, err
	}
	jwtConfig := config.ProvideJWTConfig(staticConfig)
	manager, err := jwt.NewManager(jwtConfig)
	if err != nil {
		return nil, err
	}
	databaseConfig := config.ProvideDBConfig(staticConfig)
	db, err := database.NewDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(db)
	auth := middleware.NewAuth(manager, userRepo)
	settingRepo := repo.NewSettingRepo(db)
	redisConfig := config.ProvideRedisConfig(staticConfig)
	client, err := redis.NewOptionalClient(redisConfig)
	if err != nil {
		return nil, err
	}
	cacheCache, err := cache.NewCache(client)
	if err != nil {
		return nil, err
	}
	settingService, err := service.NewSettingService(db, settingRepo, cacheCache)
	if err != nil {
		return nil, err
	}
	allCaptchaConfig := config.ProvideCaptchaConfig(staticConfig)
	httpClient := captcha.NewHttpClient()
	verifier, err := captcha.NewVerifier(allCaptchaConfig, httpClient)
	if err != nil {
		return nil, err
	}
	authService := service.NewAuthService(userRepo, settingService, manager, verifier)
	authHandler := handler.NewAuthHandler(authService)
	captchaConfigService := service.NewCaptchaConfigService(allCaptchaConfig)
	captchaHandler := handler.NewCaptchaHandler(captchaConfigService)
	storageConfig := config.ProvideStorageConfig(staticConfig)
	storageManager, err := storage.NewManager(storageConfig)
	if err != nil {
		return nil, err
	}
	tokenConfig := config.ProvideTokenConfig(staticConfig)
	tokenManager, err := token.NewManager(tokenConfig, client)
	if err != nil {
		return nil, err
	}
	emailConfig := config.ProvideEmailConfig(staticConfig)
	emailClient, err := email.NewClient(emailConfig)
	if err != nil {
		return nil, err
	}
	emailService := service.NewEmailService(emailClient, settingService)
	userService := service.NewUserService(userRepo, storageManager, settingService, tokenManager, emailService)
	userHandler := handler.NewUserHandler(userService)
	userAdminHandler := handler.NewUserAdminHandler(userService)
	attachmentRepo := repo.NewAttachmentRepo(db)
	attachmentService := service.NewAttachmentService(attachmentRepo, userRepo, storageManager, settingService)
	attachmentHandler := handler.NewAttachmentHandler(attachmentService)
	attachmentAdminHandler := handler.NewAttachmentAdminHandler(attachmentService)
	commentRepo := repo.NewCommentRepo(db)
	postRepo := repo.NewPostRepo(db)
	commentService := service.NewCommentService(commentRepo, postRepo, userRepo)
	commentHandler := handler.NewCommentHandler(commentService)
	commentAdminHandler := handler.NewCommentAdminHandler(commentService)
	tagRepo := repo.NewTagRepo(db)
	postService := service.NewPostService(postRepo, tagRepo)
	postAdminHandler := handler.NewPostAdminHandler(postService)
	settingAdminHandler := handler.NewSettingAdminHandler(settingService)
	app := NewApp(staticConfig, auth, authHandler, captchaHandler, userHandler, userAdminHandler, attachmentHandler, attachmentAdminHandler, commentHandler, commentAdminHandler, postAdminHandler, settingAdminHandler)
	return app, nil
}
