// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"easydrop/internal/config"
	"easydrop/internal/handler"
	"easydrop/internal/middleware"
	"easydrop/internal/pkg/cache"
	"easydrop/internal/pkg/captcha"
	"easydrop/internal/pkg/cookie"
	"easydrop/internal/pkg/database"
	"easydrop/internal/pkg/email"
	"easydrop/internal/pkg/jwt"
	"easydrop/internal/pkg/ratelimit"
	"easydrop/internal/pkg/redis"
	"easydrop/internal/pkg/storage"
	"easydrop/internal/pkg/token"
	"easydrop/internal/repo"
	"easydrop/internal/service"
)

// Injectors from wire.go:

// Initialize 通过 Wire 组装应用依赖。
func Initialize(configDir string, strict bool) (*App, error) {
	staticConfig, err := config.Load(configDir, strict)
	if err != nil {
		return nil, err
	}
	jwtConfig := config.ProvideJWTConfig(staticConfig)
	manager, err := jwt.NewManager(jwtConfig)
	if err != nil {
		return nil, err
	}
	databaseConfig := config.ProvideDBConfig(staticConfig)
	db, err := database.NewDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(db)
	cookieConfig := config.ProvideAuthCookieConfig(staticConfig)
	authCookie := cookie.NewAuthCookie(cookieConfig)
	auth := middleware.NewAuth(manager, userRepo, authCookie)
	securityHeaders := middleware.NewSecurityHeaders()
	ratelimitConfig := config.ProvideRateLimitConfig(staticConfig)
	redisConfig := config.ProvideRedisConfig(staticConfig)
	client, err := redis.NewOptionalClient(redisConfig)
	if err != nil {
		return nil, err
	}
	limiter, err := ratelimit.NewLimiter(ratelimitConfig, client)
	if err != nil {
		return nil, err
	}
	rateLimit := middleware.NewRateLimit(ratelimitConfig, limiter)
	settingRepo := repo.NewSettingRepo(db)
	cacheCache, err := cache.NewCache(client)
	if err != nil {
		return nil, err
	}
	settingService, err := service.NewSettingService(db, settingRepo, cacheCache)
	if err != nil {
		return nil, err
	}
	requestBodyLimit := middleware.NewRequestBodyLimit(settingService)
	allCaptchaConfig := config.ProvideCaptchaConfig(staticConfig)
	httpClient := captcha.NewHttpClient()
	verifier, err := captcha.NewVerifier(allCaptchaConfig, httpClient)
	if err != nil {
		return nil, err
	}
	tokenConfig := config.ProvideTokenConfig(staticConfig)
	tokenManager, err := token.NewManager(tokenConfig, client)
	if err != nil {
		return nil, err
	}
	emailConfig := config.ProvideEmailConfig(staticConfig)
	emailClient, err := email.NewClient(emailConfig)
	if err != nil {
		return nil, err
	}
	emailService := service.NewEmailService(emailClient, settingService)
	authService := service.NewAuthService(userRepo, settingService, manager, verifier, tokenManager, emailService)
	storageConfig := config.ProvideStorageConfig(staticConfig)
	storageManager, err := storage.NewManager(storageConfig)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepo, storageManager, settingService, tokenManager, emailService)
	authHandler := handler.NewAuthHandler(authService, userService, authCookie)
	captchaConfigService := service.NewCaptchaConfigService(allCaptchaConfig)
	captchaHandler := handler.NewCaptchaHandler(captchaConfigService)
	initRepo := repo.NewInitRepo(db)
	initService := service.NewInitService(userRepo, initRepo, settingService, cacheCache)
	initHandler := handler.NewInitHandler(initService)
	userHandler := handler.NewUserHandler(userService)
	userAdminHandler := handler.NewUserAdminHandler(userService)
	attachmentRepo := repo.NewAttachmentRepo(db)
	attachmentService := service.NewAttachmentService(attachmentRepo, userRepo, storageManager, settingService)
	attachmentHandler := handler.NewAttachmentHandler(attachmentService, settingService)
	attachmentAdminHandler := handler.NewAttachmentAdminHandler(attachmentService)
	commentRepo := repo.NewCommentRepo(db)
	postRepo := repo.NewPostRepo(db)
	postVisibilityPolicy := service.NewPostVisibilityPolicy()
	commentService := service.NewCommentService(commentRepo, postRepo, userRepo, storageManager, postVisibilityPolicy)
	commentHandler := handler.NewCommentHandler(commentService)
	commentAdminHandler := handler.NewCommentAdminHandler(commentService)
	overviewRepo := repo.NewOverviewRepo(db)
	adminOverviewService := service.NewAdminOverviewService(overviewRepo)
	overviewAdminHandler := handler.NewOverviewAdminHandler(adminOverviewService)
	tagRepo := repo.NewTagRepo(db)
	postService := service.NewPostService(postRepo, commentRepo, tagRepo, storageManager)
	postAdminHandler := handler.NewPostAdminHandler(postService)
	postHandler := handler.NewPostHandler(postService)
	settingAdminHandler := handler.NewSettingAdminHandler(settingService)
	tagService := service.NewTagService(tagRepo)
	tagHandler := handler.NewTagHandler(tagService)
	app := NewApp(staticConfig, auth, securityHeaders, rateLimit, requestBodyLimit, authHandler, captchaHandler, initHandler, userHandler, userAdminHandler, attachmentHandler, attachmentAdminHandler, commentHandler, commentAdminHandler, overviewAdminHandler, postAdminHandler, postHandler, settingAdminHandler, tagHandler)
	return app, nil
}
